# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e7af466a8cce4b1cbe9c9e700d6730063ddbfb80cd7f92639ae08808b560d6ad2cb6005e02a620f33d7b4c5cff42852328157a587bf9e02a21f144c0b10e36

test:
  secret_key_base: ae1a1381f916e43beab84c27fe7d6fb191c159e217a239b25931144a2ed72c7530c974cf2ec0c1a55aa6634fc68808b4bab108357e7bf12904a6eadc861b280c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
